### ISSUE TITLE
GPDC - ParCorr different color links

### ISSUE THREAD

**Issue by lcastri** [jakobrunge/tigramite#151]
Hi Jakob,

I have the following system:
```
var_names = [r'$d_x$', r'$v_r$', r'$v_h$']

# noise definition
np.random.seed(1)
noise = np.random.normal(0, 0.05, (T, 3))

# sys init condition
data = np.zeros((T, 3))
data[0, 0] = 15 + noise[0, 0]
data[0, 1] = 0 + noise[0, 1]
data[0, 2] = 0 + noise[0, 2]

# sys evolution
for t in range(1, T):
    data[t, 0] = data[t - 1, 0] + DT * (data[t - 1, 2] - data[t - 1, 1]) + noise[t, 0]
    data[t, 1] = 0.5 * data[t - 1, 0] + noise[t, 1]
    data[t, 2] = 0.5 * (data[t - 1, 0] ** -2) + noise[t, 2]
```

Which generate the following data:

![data](https://user-images.githubusercontent.com/87081572/135265474-17d775e4-d321-4492-b81d-f8840f842b72.png)

Since the system is nonlinear and I have additive noise, I ran the PCMCI with GPDC independence tests and I got the following result:

![GPDC_TS](https://user-images.githubusercontent.com/87081572/135266102-30a174b2-f700-4a14-92b0-fd21447cddae.png)

the algorithm detects the links:
-  from v_r[t-1] to d_x[t]
-  from d_x[t-1] to v_h[t]

but they are detected as positive effect instead of negative.

I also ran the same simulation with ParCorr independence tests and I obtained the following result:

![ParCorr_TS](https://user-images.githubusercontent.com/87081572/135267357-97030b70-3907-47ad-b1a3-befe37758a62.png)

Here, those links are detected correctly, but an auto-correlation link on v_h is wrongly detected due to the non-linearity.

Is GPDC able to detect blue links? Am I breaking any assumptions?

Thanks in advance for your help,
Luca

**Comment by jakobrunge** [comment]
The color "blue" indicates negative values of partial correlation. GPDC's values are coming from distance correlation and there cannot be a negative distance correlation since it doesn't make sense. Just as there is no negative mutual information for CMIknn. You can only define a negative slope in the linear world. If you want to detect nonlinear dependencies, then there is no such thing as a negative nonlinearity. That is why the blue-red colormap only makes sense for partial correlation.

Partial correlation can detect some aspects of nonlinear dependencies, that is why it still detects the "blue" link here and it is blue because the slope fitted by ParCorr is negative here since a linear approximation to the nonlinear dependency has a negative slope.
