### ISSUE TITLE
Development branch: PCMCI+ plot notation

### ISSUE THREAD

**Issue by jjakenichol** [jakobrunge/tigramite#166]
I noticed that in the development branch, PCMCI+ now produces plots with directed arrows, straight links with circles on the ends, and straight links with Xs on the ends. In the master branch, I believe there are only the first two. Circle links should indicate there is a contemporaneous link and the direction could not be inferred. What do the links with Xs mean?

I looked through the documentation on the development code but I know that documentation often comes last when you're trying to get features out - still, apologies if I missed it there. 

Thanks!

**Comment by jakobrunge** [comment]
x-x should only occur for pcmciplus and denotes a conflicting, contemporaneous adjacency indicating that the directionality is undecided due to conflicting orientation rules

See here: https://github.com/jakobrunge/tigramite/blob/master/tutorials/tigramite_tutorial_pcmciplus.ipynb

But please let me know if this occurs for run_pcmci()!

**Comment by jjakenichol** [comment]
Ah sorry I meant that this was occurring in PCMCI+. I also didn't notice it's detailed in the tutorial. 

What should I infer from a x-x link? Conflicting orientation rules tells me that perhaps an assumption isn't being met - or there's a subsampling problem.

**Comment by jakobrunge** [comment]
Such conflicts can indeed be due to a violation of assumptions (potentially also sub-sampling, but I didn't think further about that one), but also just due to finite sample effects...

**Comment by jjakenichol** [comment]
That makes sense, thank you.
