### ISSUE TITLE
k value convergence with LPCMCI

### ISSUE THREAD

**Issue by augo92** [jakobrunge/tigramite#167]
Hello,
I have been experimenting with LPCMCI k values. Using the same data set, I have experiment 1, which contains all data set variables, and experiment 2 containing a subset of the same variables.

Accuracy for Experiment 2 converges at k=4 and then plateaus as k gets larger. Experiment 1, however, seems to be all over the place. It always has a lower mean square error than Experiment 2, but does not converge as k increases (it gets worse after k=5 with no clear trend).

Should I expect larger k to always perform better? If so, I’m wondering what might cause the accuracy to get worse.
I should note that I was not very careful about meeting all causal assumptions with this dataset, so I assume it is due to some violation. However, given that it is difficult to ensure all assumptions hold for a given data set, I’m interested in any guidance on what non-converging k-values might mean.

Note: If the non-convergence is unexpected, then the issue could be that the ground truth cause-effect pairs I am using to measure accuracy may be wrong. However, some of the estimated causes seem unlikely given what I know about the data.

Thanks,
augo92

**Comment by Andreas-Gerhardus** [comment]
Hello augo92,

Thanks for your interest in LPCMCI!

In our numerical experiments we find that the performance increases and eventually plateaus as k gets larger. On real data, where assumptions may be violated, I suspect there indeed might be other effects.

To help me give you a more informed answer and advice, could you share some more information on your experiments and their evaluation? In particular:
- How exactly do you measure accuracy? (With respect to the presence/absence of edges only or also taking into account edge orientation? With respect to directed edges only or also bidirected edges?)
- Is there some pattern in the changes of the graph for experiment 1 when k increase further above k=5? (For example: Do more and more superfluous edges appear? Do more and more tail marks appear?)
- How do you measure MSE?
- How many variables, time steps, and samples are we talking about?

Regarding the ground truth cause-effect pairs used for measuring accuracy: The interpretation of DPAGs (the type of graph learned by LPCMCI) can sometimes be difficult, especially regarding the presence and absence of edges. For example, you might have X —> Y although the causal influence of X on Y is only indirect. For this you may consult the tutorial on LPCMCI, https://github.com/jakobrunge/tigramite/blob/developer/tutorials/tigramite_tutorial_latent-pcmci.ipynb,  especially sections 1.2 and 1.2.1.

Best

**Comment by augo92** [comment]
Hello Andreas-Gerhardus,
Thank you for your response.

- How exactly do you measure accuracy? (With respect to the presence/absence of edges only or also taking into account edge orientation? With respect to directed edges only or also bidirected edges?) -Yes, I am using directed edges.
- Is there some pattern in the changes of the graph for experiment 1 when k increase further above k=5? (For example: Do more and more superfluous edges appear? Do more and more tail marks appear?) -There is no obvious pattern.
- How do you measure MSE? -The Ground Truth is an adjacency matrix, where significant causal values are treated as 1s (otherwise 0s).
- How many variables, time steps, and samples are we talking about? 8 variables, 10^4 time steps. I'm not sure what you mean by samples, since each time step has a value for all variables. If you mean expected number of causal events in the data, it depends on the variable, but the lowest are about 8 events.

I will look at the LPCMCI tutorial, thanks for the link!
-augo92

**Comment by Andreas-Gerhardus** [comment]
Sorry, my question was indeed unclear. With ‚samples‘ I meant the time series length (so 10^4 in your case) and with ‚time steps‘ the tau_max parameter. What is tau_max in your case?

As of now, I see two possible explanations for your observations:
1. While we did not observe such behaviour in our simulation studies, it could in principle be that statistical finite sample effects lead to decreased performance for larger k in your example.
2. You may be scoring the result with respect to an adjacency matrix that does not contain all directed edges which are part of the ground truth DMAG / DPAG As I said in my previous post and which is why I referred you to the tutorial, DMAGs / DPAGs can contain additional directed edges that are counterintuitive at first. Please let me know if you have question on the tutorial.

For further analysis it would be useful to see how the true positive rate and the false positive rate behave as k increases.

As an alternative, in case you would prefer to just get some value to work with, it seems reasonable to me to choose the k that works best on the full or the restricted dataset.

What do you mean with ‚number of causal events‘  ?

Best wishes!

PS: I will be disconnecting for about 1.5 weeks.
