### ISSUE TITLE
Different linestyle for undirected links

### ISSUE THREAD

**Issue by kuchaale** [jakobrunge/tigramite#17]
It may be useful to add an option modifying the linestyle attribute for undirected (lag = 0) links, e.g.:
`tp.plot_graph(
    val_matrix=results['val_matrix'],
    link_matrix=link_matrix,
    var_names=var_names,
    link_colorbar_label='cross-MCI',
    node_colorbar_label='auto-MCI',
    show_colorbar = False,
    undirected_linestyle='dotted'
    )`
would result in:
![obrazek](https://user-images.githubusercontent.com/6815953/35509309-fcb8109e-04f3-11e8-9660-c54bc2e6910b.png)

**Comment by jakobrunge** [comment]
I just published a new release, but that part I didn't manage to change yet. I currently use the solid line style to be consistent with definitions in my papers e.g., 
J. Runge (2015): Quantifying information transfer and mediation along causal pathways in complex systems. Phys. Rev. E, 92(6), 62829. http://doi.org/10.1103/PhysRevE.92.062829

I wanted to make it flexible, but matplotlib.patches.FancyArrowPatch would not allow me to use other linestyles than 'solid' it seems. At least I couldn't get it to work for now. In general, I would love to have a more flexible graph visualization that still is based on matplotlib. Networkx unfortunately has no curved edged which are highly useful to distinguish otherwise overlapping edged. 

If you want to contribute here, that would be great!
