### ISSUE TITLE
LPCMCI edges color

### ISSUE THREAD

**Issue by christianreiser** [jakobrunge/tigramite#173]
Hi, and thank you for your work!

Your [tutorial of LPCMCI](https://github.com/jakobrunge/tigramite/blob/developer/tutorials/tigramite_tutorial_latent-pcmci.ipynb) says:

> The edges are colored according to the test statistic values returned by LPCMCI.run_lpcmci_experimental, i.e., the value of val_matrix[i, j, tau] determines the color of the edge [...]

However, all links are blue due to -inf values in the val_matrix.
Is the reason that the minimal test statistic value (e.g., minimal partial correlation coefficient) is not yet used to update the val_matrix?.

Cheers 
Chris

**Comment by Andreas-Gerhardus** [comment]
Hi Chris,

thanks for your interest in our work!

Can you please share
1. code that shows your call to LPCMCI.run_lpcmci_experimental, including the values of arguments that are passed to it, and
2.the dictionary that is returned by this call and
3. the code that generates your plot?

Whenever a -inf value is written to an element of the 'val_matrix', the corresponding edge is deleted from the 'graph' (i.e., set to the empty string). That means -inf values in the 'val_matrix' should have no effect on the plotting.

To see where the problem lies, I would kindly appreciate above information.

Kind regards,
Andreas
