### ISSUE TITLE
Getting better results on PCMCI  than SVARRFCI, LPCMCI, PCMCI+, is there something not implemented on newer methods

### ISSUE THREAD

**Issue by dynamite9999** [jakobrunge/tigramite#189]
Hello,

I am getting surprisingly better accuracy results with PCMCI than all others. Which is surprising, since the new algorithms are supposed to be better. I define accuracy as the number of correct estimated directed edges/ true correct directed edges per node. 

SETUP:
tigramite - 4.2.2.1
I am varying knn, which makes a huge difference[.05, .2, .4] and cannot figure out why having a smaller hypercube would yield better results. I am only using CMIknn[varying knn as noted above] and keeping tau_max=[4,6],  pc_alpha:0.2 alpha_level:0.05  fixed_thresh: 0.8.

QUESTIONS:
1. why does a smaller knn for CMIknn at .05 yield better results  than larger values ? I must be missing something. If anything, making the hypercube larger, with more data would yield higher power due to larger number of samples ? Please help me clarify?
2. I have tried fixed_thresh of 10, 20 and it ran much faster, which no real changes, however the recommended values are are at .2. I am getting better accuracy at .8. I am not really understanding why ? Please help me understand what is this parameter does and how such large values are faster ? Is there caching effect perhaps ?
3. I have tested with all kinds of data [non, ]distributions stationary, gaussian, linearand thought to get better results with pcmci+ and svarrfci as per paper, but I am seeing opposite. Any fixes that I am missing perhaps since 4.2.2.1 ?

Any clarifications would be very much appreciated.

Cheers,

Giselle

**Comment by sagarsimha** [comment]
Hello. We are looking into your question. Will respond with observations on the discussion channel.

**Comment by jakobrunge** [comment]
Ad 1) There is no easily explainable impact of knn on causal discovery. It is more a choice you make based on your background knowledge. Too small knn lead to high variance, too large knn lead to more bias. Both of these impact individual independence tests and subsequently PCMCI.

Ad 2) fixed_thres implies that NO shuffle test is used, which is much faster. You have to set significance='fixed_thres', though. 0.2 is not the default for fixed thres, it is 0.1 and just a rough value. knn=0.8 means that knn=0.8*n where n is the sample size, knn=30 means knn=30. I.e., if knn<1, then it is interpreted as a fraction, otherwise as the knn-value.

ad 3) All these choices are not just some hyperparameter as in deep learning, but they are your assumptions about the process. causal discovery is fundamentally different from just (over-)fitting a model.

Still, check out the new Master!
